export type LabelTemplate = {
  id: string
  name: string
  pageFormat: string
  pageWidth: number
  pageHeight: number
  unit: string
  marginTop: number
  marginLeft: number
  labelWidth: number
  labelHeight: number
  horizontalPitch: number
  verticalPitch: number
  columns: number
  rows: number
  radius: number
}

export const shippingLabelData_ISO: LabelTemplate[] = [
  {
    "id": "avery-3490",
    "name": "Avery Zweckform 3490",
    "pageFormat": "A4",
    "unit": "mm",
    "pageWidth": 210,
    "pageHeight": 297,
    "marginTop": 4.5,
    "marginLeft": 0,
    "labelWidth": 70,
    "labelHeight": 36,
    "horizontalPitch": 70,
    "verticalPitch": 36,
    "columns": 3,
    "rows": 8,
    "radius": 0
  },
   {
    "id": "avery-3422",
    "name": "Avery Zweckform 3422",
    "pageFormat": "A4",
    "unit": "mm",
    "pageWidth": 210,
    "pageHeight": 297,
    "marginTop": 8.5,
    "marginLeft": 0,
    "labelWidth": 70,
    "labelHeight": 35,
    "horizontalPitch": 70,
    "verticalPitch": 35,
    "columns": 3,
    "rows": 8,
    "radius": 0
  },
   {
    "id": "avery-L4736REV",
    "name": "Avery Zweckform L4736REV",
    "pageFormat": "A4",
    "unit": "mm",
    "pageWidth": 210,
    "pageHeight": 297,
    "marginTop": 21.5,
    "marginLeft": 9.7,
    "labelWidth": 45.7,
    "labelHeight": 21.2,
    "horizontalPitch": 48.3,
    "verticalPitch": 21.2,
    "columns": 4,
    "rows": 12,
    "radius": 0
  },
  {
    "id": "avery-6126",
    "name": "Avery Zweckform 6126",
    "pageFormat": "A4",
    "unit": "mm",
    "pageWidth": 210,
    "pageHeight": 297,
    "marginTop": 21.5,
    "marginLeft": 8,
    "labelWidth": 48.5,
    "labelHeight": 25.4,
    "horizontalPitch": 48.5,
    "verticalPitch": 25.4,
    "columns": 4,
    "rows": 10,
    "radius": 0
  },
   {
    "id": "avery-L7912",
    "name": "Avery Zweckform L7912",
    "pageFormat": "A4",
    "unit": "mm",
    "pageWidth": 210,
    "pageHeight": 297,
    "marginTop": 12,
    "marginLeft": 6.4,
    "labelWidth": 63.5,
    "labelHeight": 33.9,
    "horizontalPitch": 66,
    "verticalPitch": 33.9,
    "columns": 3,
    "rows": 8,
    "radius": 0
  },
     {
    "id": "avery-L3415",
    "name": "Avery Zweckform L3415",
    "pageFormat": "A4",
    "unit": "mm",
    "pageWidth": 210,
    "pageHeight": 297,
    "marginTop": 13.5,
    "marginLeft": 16,
    "labelWidth": 40,
    "labelHeight": 40,
    "horizontalPitch": 46,
    "verticalPitch": 46,
    "columns": 4,
    "rows": 6,
    "radius": 100
  },
    {
    "id": "avery-LR3475",
    "name": "Avery Zweckform LR3475",
    "pageFormat": "A4",
    "unit": "mm",
    "pageWidth": 210,
    "pageHeight": 297,
    "marginTop": 4.5,
    "marginLeft": 0,
    "labelWidth": 70,
    "labelHeight": 36,
    "horizontalPitch": 70,
    "verticalPitch": 36,
    "columns": 3,
    "rows": 8,
    "radius": 0
  },
    {
    "id": "avery-3454",
    "name": "Avery Zweckform 3454",
    "pageFormat": "A4",
    "unit": "mm",
    "pageWidth": 210,
    "pageHeight": 297,
    "marginTop": 0,
    "marginLeft": 0,
    "labelWidth": 105,
    "labelHeight": 37.1,
    "horizontalPitch": 105,
    "verticalPitch": 37.1,
    "columns": 2,
    "rows": 8,
    "radius": 0
  },
    {
    "id": "avery-4781",
    "name": "Avery Zweckform 4781",
    "pageFormat": "A4",
    "unit": "mm",
    "pageWidth": 210,
    "pageHeight": 297,
    "marginTop": 21.6,
    "marginLeft": 8,
    "labelWidth": 97,
    "labelHeight": 42.3,
    "horizontalPitch": 97,
    "verticalPitch": 42.3,
    "columns": 2,
    "rows": 6,
    "radius": 0
  },
    {
    "id": "avery-L4772",
    "name": "Avery Zweckform L4772",
    "pageFormat": "A4",
    "unit": "mm",
    "pageWidth": 210,
    "pageHeight": 297,
    "marginTop": 21.4,
    "marginLeft": 4.7,
    "labelWidth": 99,
    "labelHeight": 42.3,
    "horizontalPitch": 101.6,
    "verticalPitch": 42.3,
    "columns": 2,
    "rows": 6,
    "radius": 0
  },
   {
    "id": "avery-L6041",
    "name": "Avery Zweckform L6041",
    "pageFormat": "A4",
    "unit": "mm",
    "pageWidth": 210,
    "pageHeight": 297,
    "marginTop": 21.5,
    "marginLeft": 9.7,
    "labelWidth": 45.7,
    "labelHeight": 21.2,
    "horizontalPitch": 48.3,
    "verticalPitch": 21.2,
    "columns": 4,
    "rows": 12,
    "radius": 0
  },
   {
    "id": "avery-L6004",
    "name": "Avery Zweckform L6004",
    "pageFormat": "A4",
    "unit": "mm",
    "pageWidth": 210,
    "pageHeight": 297,
    "marginTop": 15.1,
    "marginLeft": 7.2,
    "labelWidth": 63.5,
    "labelHeight": 29.6,
    "horizontalPitch": 66,
    "verticalPitch": 29.6,
    "columns": 3,
    "rows": 9,
    "radius": 0
  },
   {
    "id": "avery-J4721",
    "name": "Avery Zweckform J4721",
    "pageFormat": "A4",
    "unit": "mm",
    "pageWidth": 210,
    "pageHeight": 297,
    "marginTop": 15.1,
    "marginLeft": 7.2,
    "labelWidth": 63.5,
    "labelHeight": 29.6,
    "horizontalPitch": 66,
    "verticalPitch": 29.6,
    "columns": 3,
    "rows": 8,
    "radius": 0
  },
   {
    "id": "avery-L4732REV",
    "name": "Avery Zweckform L4732REV",
    "pageFormat": "A4",
    "unit": "mm",
    "pageWidth": 210,
    "pageHeight": 297,
    "marginTop": 13.1,
    "marginLeft": 11,
    "labelWidth": 35.6,
    "labelHeight": 16.9,
    "horizontalPitch": 38.1,
    "verticalPitch": 16.9,
    "columns": 5,
    "rows": 16,
    "radius": 0
  },
   {
    "id": "avery-L7160",
    "name": "Avery Zweckform L7160",
    "pageFormat": "A4",
    "unit": "mm",
    "pageWidth": 210,
    "pageHeight": 297,
    "marginTop": 15.1,
    "marginLeft": 7.2,
    "labelWidth": 63.5,
    "labelHeight": 38.1,
    "horizontalPitch": 66,
    "verticalPitch": 38.1,
    "columns": 3,
    "rows": 7,
    "radius": 0
  },
   {
    "id": "avery-L6021REV",
    "name": "Avery Zweckform L6021REV",
    "pageFormat": "A4",
    "unit": "mm",
    "pageWidth": 210,
    "pageHeight": 297,
    "marginTop": 13.1,
    "marginLeft": 9.7,
    "labelWidth": 45.7,
    "labelHeight": 16.9,
    "horizontalPitch": 48.3,
    "verticalPitch": 16.9,
    "columns": 4,
    "rows": 16,
    "radius": 0
  },
   {
    "id": "avery-L7651",
    "name": "Avery Zweckform L7651",
    "pageFormat": "A4",
    "unit": "mm",
    "pageWidth": 210,
    "pageHeight": 297,
    "marginTop": 10.9,
    "marginLeft": 4.7,
    "labelWidth": 38.1,
    "labelHeight": 21.2,
    "horizontalPitch": 40.6,
    "verticalPitch": 21.2,
    "columns": 5,
    "rows": 13,
    "radius": 0
  },
   {
    "id": "avery-L6048",
    "name": "Avery Zweckform L6048",
    "pageFormat": "A4",
    "unit": "mm",
    "pageWidth": 210,
    "pageHeight": 297,
    "marginTop": 13.5,
    "marginLeft": 8.5,
    "labelWidth": 25.4,
    "labelHeight": 10,
    "horizontalPitch": 27.9,
    "verticalPitch": 10,
    "columns": 7,
    "rows": 27,
    "radius": 0
  },
   {
    "id": "avery-C6080",
    "name": "Avery Zweckform C6080",
    "pageFormat": "A4",
    "unit": "mm",
    "pageWidth": 210,
    "pageHeight": 297,
    "marginTop": 23.6,
    "marginLeft": 7.2,
    "labelWidth": 63.5,
    "labelHeight": 46.6,
    "horizontalPitch": 66,
    "verticalPitch": 50.8,
    "columns": 3,
    "rows": 5,
    "radius": 0
  },
   {
    "id": "avery-3451",
    "name": "Avery Zweckform 3451",
    "pageFormat": "A4",
    "unit": "mm",
    "pageWidth": 210,
    "pageHeight": 297,
    "marginTop": 0,
    "marginLeft": 0,
    "labelWidth": 70,
    "labelHeight": 37.1,
    "horizontalPitch": 70,
    "verticalPitch": 37.1,
    "columns": 3,
    "rows": 8,
    "radius": 0
  },
   {
    "id": "avery-L7263",
    "name": "Avery Zweckform L7263",
    "pageFormat": "A4",
    "unit": "mm",
    "pageWidth": 210,
    "pageHeight": 297,
    "marginTop": 15.1,
    "marginLeft": 4.7,
    "labelWidth": 99,
    "labelHeight": 38.1,
    "horizontalPitch": 101.6,
    "verticalPitch": 38.1,
    "columns": 2,
    "rows": 7,
    "radius": 0
  },
   {
    "id": "avery-L6145",
    "name": "Avery Zweckform L6145",
    "pageFormat": "A4",
    "unit": "mm",
    "pageWidth": 210,
    "pageHeight": 297,
    "marginTop": 21.4,
    "marginLeft": 9.7,
    "labelWidth": 45.7,
    "labelHeight": 25.4,
    "horizontalPitch": 48.3,
    "verticalPitch": 25.4,
    "columns": 4,
    "rows": 10,
    "radius": 0
  },
]

export const shippingLabelData_US: LabelTemplate[] = [
  {
    "id": "avery-5160",
    "name": "Avery 5160",
    "pageFormat": "US Letter",
    "unit": "mm",
    "pageWidth": 215.9,
    "pageHeight": 279.4,
    "marginTop": 12.7,
    "marginLeft": 4.8,
    "labelWidth": 66.8,
    "labelHeight": 25.4,
    "horizontalPitch": 69.8,
    "verticalPitch": 25.4,
    "columns": 3,
    "rows": 10,
    "radius": 0
  },
  {
    "id": "avery-8160",
    "name": "Avery 8160",
    "pageFormat": "US Letter",
    "unit": "mm",
    "pageWidth": 215.9,
    "pageHeight": 279.4,
    "marginTop": 12.7,
    "marginLeft": 4.8,
    "labelWidth": 66.8,
    "labelHeight": 25.4,
    "horizontalPitch": 69.8,
    "verticalPitch": 25.4,
    "columns": 3,
    "rows": 10,
    "radius": 0
  },
  {
    "id": "avery-5260",
    "name": "Avery 5260",
    "pageFormat": "US Letter",
    "unit": "mm",
    "pageWidth": 215.9,
    "pageHeight": 279.4,
    "marginTop": 12.7,
    "marginLeft": 4.8,
    "labelWidth": 66.8,
    "labelHeight": 25.4,
    "horizontalPitch": 69.8,
    "verticalPitch": 25.4,
    "columns": 3,
    "rows": 10,
    "radius": 0
  },
  {
    "id": "avery-5161",
    "name": "Avery 5161",
    "pageFormat": "US Letter",
    "unit": "mm",
    "pageWidth": 215.9,
    "pageHeight": 279.4,
    "marginTop": 12.7,
    "marginLeft": 4.2,
    "labelWidth": 101.6,
    "labelHeight": 25.4,
    "horizontalPitch": 106.3,
    "verticalPitch": 25.4,
    "columns": 2,
    "rows": 10,
    "radius": 0
  },
]