import { AccessoryType_Optic } from "interfaces"
import { SimpleTranslation } from "lib/textTemplates";

type TemplateKeys = keyof Omit<AccessoryType_Optic, "id" | "createdAt" | "lastModifiedAt" | "db_id" | "tags" | "images" | "remarks">;

type TemplateItem = {
    name: TemplateKeys
} & SimpleTranslation;


export const accessoryDataTemplate_Optic:TemplateItem[] = [
    {
            name: "manufacturer",
            de: "Hersteller",
            en: "Manufacturer",
            fr: "Fabricant",
            it: "Produttore",
            ch: "Producent",
    },
    {   
            name: "model",
            de: "Modellbezeichnung",
            en: "Model Name",
            fr: "Désignation du modèle",
            it: "Nome del modello",
            ch: "Designaziun dal model",
            },
    {
            name: "manufacturingDate",
            de: "Herstellungszeitraum",
            en: "Manufacturing Date",
            fr: "Période de fabrication",
            it: "Periodo di produzione",
            ch: "Perioda da producziun",
    },
    {
            name: "originCountry",
            de: "Ursprungsland",    
            en: "Origin Country",
            fr: "Pays d'origine",
            it: "Paese di origine",
            ch: "Pajais d'origin",
    },
    {   
            name: "serial",
            de: "Seriennummer",
            en: "Serial",
            fr: "Numéro de série",
            it: "Numero di serie",
            ch: "Numer da seria",
    },
    {   
            name: "reticle",
            de: "Absehen",
            en: "Reticle",
            fr: "",
            it: "",
            ch: "",
    },
    {   
            name: "reticleColor",
            de: "Absehen Farbe",
            en: "Reticle Color",
            fr: "",
            it: "",
            ch: "",
    },
    {   
            name: "zoom",
            de: "Vergrösserung",
            en: "Zoom",
            fr: "",
            it: "",
            ch: "",
    },
    {   
            name: "unit",
            de: "Verstelleinheit",
            en: "Click Unit",
            fr: "",
            it: "",
            ch: "",
    },
    {   
            name: "clicksToUnitElevation",
            de: "Höhenverstellung pro Klick",
            en: "Elevation Adjustment per Click",
            fr: "",
            it: "",
            ch: "",
    },
    {   
            name: "clicksToUnitWindage",
            de: "Seitenverstellung pro Klick",
            en: "Windage Adjustment per Click",
            fr: "",
            it: "",
            ch: "",
    },
    {
            name: "material",
            de: "Material",
            en: "Material",
            fr: "La Materiala",
            it: "Il Materiale",
            ch: "Va Materiala",
    },
    {
            name: "acquisitionDate_unix",
            de: "Erwerbsdatum",     
            en: "Acquision Date",
            fr: "Date d'acquisition",
            it: "Data di acquisizione",
            ch: "Data d'acquist",
        
    },
    {
        name: "paidPrice",
        de: "Kaufpreis",     
        en: "Price",
        fr: "Prix d'achat",
        it: "Prezzo",
        ch: "Pretsch da cumpra",
    
    },
    {
        name: "boughtFrom",
        de: "Gekauft bei/von",     
        en: "Acquired from",
        fr: "Acquis auprès de/par",
        it: "Acquistati presso/da",
        ch: "Acquistà tar/da",
    },
    {
        name: "marketValue",
        de: "Aktueller Marktwert",
        en: "Current market value",
        fr: "Valeur de marché actuelle",
        it: "Valore di mercato attuale",
        ch: "Valur actuala dal martgà"
    },
    {
        name: "shotCount",
        de: "Schussbelastung",
        en: "Shot count",
        fr: "Compte de tirs",
        it: "Numero di colpi sparati",
        ch: "Chargia da tir",
    },
    {
        name: "lastShotAt_unix",
        de: "Zuletzt geschossen",
        en: "Last shot",
        fr: "Derniers tirs",
        it: "Ultimo colpo",
        ch: "L'ultim culp",
    },
    {
        name: "lastCleanedAt_unix",
        de: "Zuletzt gereinigt",
        en: "Last cleaned",
        fr: "Nettoyé en dernier",
        it: "Ultima pulizia",
        ch: "Il davos purifitgà",
    },
    {
        name: "cleanInterval",
        de: "Reinigungsintervall",
        en: "Cleaning interval",
        fr: "Intervalle de nettoyage",
        it: "Intervallo di pulizia",
        ch: "Interval da nettegiar",
    },
    {
        name: "batteryLastChangedAt_unix",
        de: "Zuletzt gereinigt",
        en: "Last cleaned",
        fr: "Nettoyé en dernier",
        it: "Ultima pulizia",
        ch: "Il davos purifitgà",
    },
    {
            name: "mainColor",
            de: "Hauptfarbe",
            en: "Main Color",
            fr: "Couleur principale",
            it: "Colore principale",
            ch: "Da colur principala",
    },
    {
            name: "currentlyMountedOn",
            de: "Montiert auf",
            en: "Mounted on",
            fr: "Morere sur",
            it: "Montare sole",
            ch: "Va montaschier sur",
    },
]

export const opticRemarks:{name:string, de:string, en:string, fr:string, it: string, ch: string} = {
    name: "remarks",
    de: "Bemerkungen",
    en: "Remarks",
    fr: "Remarques",
    it: "Osservazioni",
    ch: "Remartgar",
}

export const emptyOpticObject:AccessoryType_Optic= {
    id: "",
    manufacturer: null,
    model: "",
    manufacturingDate: null,
    originCountry: null,
    serial: null,
    reticle: null,
    reticleColor: null,
    zoom: null,
    unit: null,
    clicksToUnitElevation: null,
    clicksToUnitWindage: null,
    material: null,
    acquisitionDate_unix: null,
    boughtFrom: null,
    mainColor: null,
    remarks : null,
    images: [],
    createdAt: 0,
    lastModifiedAt: 0,
    shotCount: null,
    tags: [],
    lastShotAt_unix: null,
    lastCleanedAt_unix: null,
    paidPrice: null,
    marketValue: null,
    cleanInterval: null,
    currentlyMountedOn: null,
    batteryLastChangedAt_unix: null
}