import { AccessoryType_Silencer, PartType_ConversionKit } from "interfaces"
import { normalizeColor } from "react-native-reanimated/lib/typescript/Colors"

export const partDataTemplate_ConversionKit:{name:string, de:string, en:string, fr:string, it: string, ch: string}[] = [
    {
            name: "manufacturer",
            de: "Hersteller",
            en: "Manufacturer",
            fr: "Fabricant",
            it: "Produttore",
            ch: "Producent",
    },
    {   
            name: "model",
            de: "Modellbezeichnung",
            en: "Model Name",
            fr: "Désignation du modèle",
            it: "Nome del modello",
            ch: "Designaziun dal model",
            },
    {
            name: "manufacturingDate",
            de: "Herstellungszeitraum",
            en: "Manufacturing Date",
            fr: "Période de fabrication",
            it: "Periodo di produzione",
            ch: "Perioda da producziun",
    },
    {
            name: "originCountry",
            de: "Ursprungsland",    
            en: "Origin Country",
            fr: "Pays d'origine",
            it: "Paese di origine",
            ch: "Pajais d'origin",
    },
    {
            name: "caliber",
            de: "Kaliber",
            en: "Caliber",
            fr: "Calibre",
            it: "Calibro",
            ch: "Caliber",
    },
    {   
            name: "serial",
            de: "Seriennummer",
            en: "Serial",
            fr: "Numéro de série",
            it: "Numero di serie",
            ch: "Numer da seria",
    },
    {
            name: "permit",
            de: "Bewilligung",
            en: "Permit",
            fr: "Permis",
            it: "Permesso",
            ch: "Concessiun",
    },
    {
            name: "acquisitionDate",
            de: "Erwerbsdatum",     
            en: "Acquision Date",
            fr: "Date d'acquisition",
            it: "Data di acquisizione",
            ch: "Data d'acquist",
        
    },
    {
        name: "paidPrice",
        de: "Kaufpreis",     
        en: "Price",
        fr: "Prix d'achat",
        it: "Prezzo",
        ch: "Pretsch da cumpra",
    
    },
    {
        name: "boughtFrom",
        de: "Gekauft bei/von",     
        en: "Acquired from",
        fr: "Acquis auprès de/par",
        it: "Acquistati presso/da",
        ch: "Acquistà tar/da",
    },
    {
        name: "marketValue",
        de: "Aktueller Marktwert",
        en: "Current market value",
        fr: "Valeur de marché actuelle",
        it: "Valore di mercato attuale",
        ch: "Valur actuala dal martgà"
    },
    {
        name: "shotCount",
        de: "Schussbelastung",
        en: "Shot count",
        fr: "Compte de tirs",
        it: "Numero di colpi sparati",
        ch: "Chargia da tir",
    },
    {
        name: "lastShotAt",
        de: "Zuletzt geschossen",
        en: "Last shot",
        fr: "Derniers tirs",
        it: "Ultimo colpo",
        ch: "L'ultim culp",
    },
    {
        name: "lastCleanedAt",
        de: "Zuletzt gereinigt",
        en: "Last cleaned",
        fr: "Nettoyé en dernier",
        it: "Ultima pulizia",
        ch: "Il davos purifitgà",
    },
    {
        name: "cleanInterval",
        de: "Reinigungsintervall",
        en: "Cleaning interval",
        fr: "Intervalle de nettoyage",
        it: "Intervallo di pulizia",
        ch: "Interval da nettegiar",
    },
    {
            name: "mainColor",
            de: "Hauptfarbe",
            en: "Main Color",
            fr: "Couleur principale",
            it: "Colore principale",
            ch: "Da colur principala",
    },
    {
            name: "currentlyMountedOn",
            de: "Montiert auf",
            en: "Mounted on",
            fr: "",
            it: "",
            ch: "",
    },
]

export const conversionKitRemarks:{name:string, de:string, en:string, fr:string, it: string, ch: string} = {
    name: "remarks",
    de: "Bemerkungen",
    en: "Remarks",
    fr: "Remarques",
    it: "Osservazioni",
    ch: "Remartgar",
}

export const emptyConversionKitObject:PartType_ConversionKit= {
    id: "",
    manufacturer: null,
    model: "",
    manufacturingDate: null,
    originCountry: null,
    caliber: [],
    serial: null,
    permit: null,
    acquisitionDate: null,
    boughtFrom: null,
    mainColor: null,
    remarks : null,
    images: [],
    createdAt: 0,
    lastModifiedAt: 0,
    shotCount: null,
    tags: [],
    lastShotAt: null,
    lastCleanedAt: null,
    paidPrice: null,
    marketValue: null,
    cleanInterval: null,
    currentlyMountedOn: null,
}