import { SimpleTranslation } from "./interfaces_text"

interface ScannerNavigate{
    title: SimpleTranslation
    subtitle: SimpleTranslation
    error: SimpleTranslation
}

export const scannerNavigate: ScannerNavigate = {
    title: {
        de: "QR-Code-Navigator",
        en: "QR Code Navigator", 
        fr: "Navigateur de codes QR",
        it: "Navigatore QR Code",
        ch: "Navigatur da code QR"
    },
    subtitle: {
        de: `Scanne einen QR-Code und wähle aus, ob dieser von der App generiert wurde (Arsenal Code) oder ein eigener ist (QR Code).`,
        en: `Scan a QR Code and select if it was a code generated by the app (Arsenal Code) or is your own one (QR Code).`, 
        fr: `Scannez un code QR et sélectionnez s’il s’agit d’un code généré par l’application (Arsenal Code) ou d’un code personnel (QR Code).`,
        it: `Scansionare un codice QR e selezionare se si tratta di un codice generato dall’app (Arsenal Code) o se è un codice personale (QR Code).`,
        ch: `Scannescha in code QR e tscherna, sch’i sa tracta d’in code generà da l’app (Arsenal Code) u d’in agen code (QR Code).`
    },
    error: {
        de: "Keinen gültigen Eintrag gefunden für {{{A}}}:",
        en: "No valid entry found for {{{A}}}:", 
        fr: "Aucune entrée valide trouvée pour {{{A}}}:",
        it: "Non è stato trovato alcun elemento valido per {{{A}}}:",
        ch: "Betg chattà in’inoltraziun valaivla per {{{A}}}:"
    }
}

export const scannerInfo: SimpleTranslation = {
    de: "Existierende QR Codes scannen um diese mit dem Eintrag zu verbinden. Der Eintrag ist dann in der Sammlungsübersicht direkt aufrufbar wenn der Code gescannt wird.",
    en: "Scan your existing QR-Codes to bind them to this item. You can access an item by scanning the code in the collection view directly",
    fr: "Numérisez vos QR-Codes existants pour les associer à cet article. Vous pouvez accéder à un article en numérisant le code directement dans la vue de la collection.",
    it: "Scansionate i vostri codici QR esistenti per associarli a questo articolo. Potete accedere a un articolo semplicemente scansionando il codice nella visualizzazione della collezione.",
    ch: "Scannescha tes codes da QR avant maun per als colliar cun quest artitgel. Vus pudais scannar in artitgel directamain cun la vista collectiva per avair access a quel."
}